apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: dtp-requests-base
spec:
  schedule: "*/15 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: default
          containers:
          - name: dtp-requests-base
            image: cbmckni/dtp-requests-base
            env:
            - name: ORG
              value: scidas
            - name: BRANCH
              value: {{ .Values.Requests.Branch }}
            - name: PVCNAME
              value: {{ template "pvcName" . }}
            - name: PVCPATH
              value: {{ template "pvcPath" . }}
            command: [ "/bin/bash", "-c", "--" ]
            args: [ "echo 'starting'; if [ -d /workspace/dtp-requests ]; then rm -rf /workspace/dtp-requests; fi; git clone -b {{ .Values.Requests.Branch }} https://github.com/SciDAS/dtp-requests.git /workspace/dtp-requests && cd /workspace/dtp-requests && ./update.sh; echo 'done'" ]
            resources:
              requests:
                cpu: {{ .Values.Resources.Requests.CPU }}
                memory: {{ .Values.Resources.Requests.Memory }}
              limits:
                cpu: {{ .Values.Resources.Limits.CPU }}
                memory: {{ .Values.Resources.Limits.Memory }}
            volumeMounts:
            - name: vol-1
              mountPath: {{ template "pvcPath" . }}
          restartPolicy: OnFailure
          volumes:
            - name: vol-1
              persistentVolumeClaim:
                claimName: {{ template "pvcName" . }}


# Variables

{{- define "pvcPath" -}}
{{- if .Values.NewPVC.Enabled }}{{ .Values.NewPVC.Path }}{{ else }}{{ .Values.ExistingPVC.Path }}{{ end }}
{{- end -}}

{{- define "pvcName" -}}
{{- if .Values.NewPVC.Enabled }}{{ .Values.NewPVC.Name }}{{ else }}{{ .Values.ExistingPVC.Name }}{{ end }}
{{- end -}}

